version: '3'

services:

  ui:
    build:
      context: .
      dockerfile: ui/docker/Dockerfile
    ports:
      - "10001:80"
    depends_on:
      - api
    restart: always

  api:
    build:
      context: .
      dockerfile: api/docker/Dockerfile
    ports:
      - "10000:5000"
    depends_on:
      - rabbitmq3
    restart: always

  rabbitmq3:
    image: rabbitmq:3.8-management-alpine
    environment:
        - RABBITMQ_DEFAULT_USER=mushin_user
        - RABBITMQ_DEFAULT_PASS=mushin_pass
    ports:
        - '5672:5672'
        - '15672:15672'  
