version: '3'

services:

  ui:
    build:
      context: .
      dockerfile: docker/ui.Dockerfile
    ports:
      - "10001:80"
    depends_on:
      - server
    restart: always

  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    ports:
      - "10000:8080"
    entrypoint: ["/bin/sh","-c"]
    command: 
      - | 
          celery --app server.server.celery worker --loglevel=info &
          python server/server.py
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
