version: '3'

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.22.0.0/16

services:

  ui:
    build:
      context: .
      dockerfile: ui/docker/Dockerfile
    ports:
      - "10001:80"
    depends_on:
      - api
    restart: always
    networks:
      static-network:
        ipv4_address: 172.22.128.1

  api:
    build:
      context: .
      dockerfile: api/docker/Dockerfile
    ports:
      - "10000:5000"
    restart: always
    networks:
      static-network:
        ipv4_address: 172.22.128.2