version: '3'

services:

  ui:
    build:
      context: .
      dockerfile: ui/docker/Dockerfile
    ports:
      - "10001:80"
    depends_on:
      - api
    restart: always

  api:
    build:
      context: .
      dockerfile: api/docker/Dockerfile
    ports:
      - "10000:5000"
    restart: always
